### ISSUE TITLE
Problem with Faster RCNN

### ISSUE THREAD

**Issue by fernandoFernandeSantos** [pytorchfi/pytorchfi#83]
Hello
I`m trying to use PytorchFi with Faster RCNN from torchvision models. However, the script fails when I call the print_pytorchfi_layer_summary(). Below is an example

```
import torch
from pytorchfi.core import fault_injection
from torchvision.io import read_image
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.transforms.functional import convert_image_dtype

dog_path = "assets/dog1.jpg" # it can be any other input image
dog1_int = read_image(dog_path)
input_test = convert_image_dtype(torch.stack([dog1_int]), dtype=torch.float)

batch_size, c, h, w = input_test.shape
model = fasterrcnn_resnet50_fpn(pretrained=True, progress=False)
model = model.eval()
golden = model(input_test)
print("Error-free label:", golden)

pfi_model = fault_injection(model,
                            batch_size,
                            input_shape=[c, h, w],
                            layer_types=[torch.nn.Conv2d],
                            use_cuda=False,
                            )

print(pfi_model.print_pytorchfi_layer_summary())
```

The following error happens:
```
Traceback (most recent call last):
  File "<HOMEPATH>/PycharmProjects/pytorchfi_test/small_example.py", line 25, in <module>
    print(pfi_model.print_pytorchfi_layer_summary())
  File "<HOMEPATH>/PycharmProjects/pytorchfi_test/venv/lib/python3.8/site-packages/pytorchfi/core.py", line 530, in print_pytorchfi_layer_summary
    str(list(self.weights_size[layer])),
IndexError: list index out of range
```

Any ideia why this happens?

**Comment by ma3mool** [comment]
I dug into this a bit and found something very interesting regarding the model `fasterrcnn_resnet50_fpn`.

It seems that there are more activation tensors (contributed to `torch.nn.Conv2d`) than there are weight tensors. Specifically, the code identifies 76 calls to a convolution, but there only seem to be 64 "layers" for weights. This seems like it might have more to do with the model choice.

The `print_pytorchfi_layer_summary()` assumes that there is a 1-to-1 correspondence between the weight tensor and the output layer values. Since there seems to be a mismatch here, it looks like it crashed.

Is there a particular objective you have in mind? To help direct you a bit more, you can modify the code in the `print_pytorchfi_layer_summary()` near lines [528](https://github.com/pytorchfi/pytorchfi/blob/071f0511f959662c843d4865b50f348b9f4efd27/pytorchfi/core.py#L528) to print just weights OR neuron tensors.

**Comment by fernandoFernandeSantos** [comment]
Thanks, @ma3mool

For me, it is enough that  `print_pytorchfi_layer_summary()` prints only the weights or tensors. However, I would like to evaluate the fault propagation in all layers of complex models like Faster RCNN. However, it crashes when I select to inject faults in all the layers `layer_types="all"` and try to inject a fault.
It crashes on line [414](https://github.com/pytorchfi/pytorchfi/blob/071f0511f959662c843d4865b50f348b9f4efd27/pytorchfi/core.py#L414) it generates the error
`AttributeError: 'tuple' object has no attribute 'size'`

Would you know any workaround for this issue?

**Comment by n3a9** [comment]
Hey @fernandoFernandeSantos 

Sorry for the late follow up on this – it seems that with this model the output is of type `(ImageList, None)` as opposed to the Tensor that we're looking for. Let me look into this more and see if there's a follow up here

Thanks for letting us know :D
